name: Example Push Action
on:
  push:
    branches:
     - "main"
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
      - run: |
          cp -r .git dist/
          cd dist
          git checkout --orphan build-ssg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Build"
          git push -f origin build-ssg
